version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: abcd@1234
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:

volumes:
  mongodb-data:
