
@url_dev = http://localhost:3000/v1/api
### sign up
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: 9dc3d212da98a81458a13c9f985280a8

{
    "name": "shop25",
    "email": "shop25@gmail.com",
    "password": "123456"
}